### ISSUE TITLE
Possible timing attack vulnerability

### ISSUE THREAD

**Issue by Philipp91** [realli/simple_jwt#1]
Just a quick heads-up from a passer-by:
https://github.com/realli/simple_jwt/blob/master/src/digest.rs#L27
This comparison might be vulnerable to timing attacks because it's not constant-time. Not sure if that's relevant here at all. I'm reporting such issues to a couple of repositories, please just ignore/close if it isn't applicable here.

To be on the safe side, you could just use a constant-time comparison function: https://docs.rs/openssl/0.9.4/openssl/memcmp/fn.eq.html

**Comment by realli** [comment]
@Philipp91 , you are right, I will fix that soon.
